apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-domain
spec:
  ingressClassName: nginx
  rules:
  - host: vote.votingapp.com
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-vote
            port:
              number: 8080
  - host: result.votingapp.com
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-result
            port:
              number: 8080
              